# Generated by Django 5.2 on 2025-04-16 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_workimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='name',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to='app.profile'),
            preserve_default=False,
        ),
    ]
